---
# Root requirements file
includes:
  - docs/reqstream/api-mark-core.yaml
  - docs/reqstream/api-mark-core/i-api-generator.yaml
  - docs/reqstream/api-mark-core/i-api-emitter.yaml
  - docs/reqstream/api-mark-core/emit-config.yaml
  - docs/reqstream/api-mark-core/i-context.yaml
  - docs/reqstream/api-mark-core/i-markdown-writer-factory.yaml
  - docs/reqstream/api-mark-core/file-markdown-writer-factory.yaml
  - docs/reqstream/api-mark-core/i-markdown-writer.yaml
  - docs/reqstream/api-mark-core/file-markdown-writer.yaml
  - docs/reqstream/api-mark-core/path-helpers.yaml
  - docs/reqstream/api-mark-core/glob-file-collector.yaml
  - docs/reqstream/api-mark-dot-net.yaml
  - docs/reqstream/api-mark-dot-net/dot-net-generator.yaml
  - docs/reqstream/api-mark-dot-net/type-name-simplifier.yaml
  - docs/reqstream/api-mark-dot-net/dot-net-ast-model.yaml
  - docs/reqstream/api-mark-dot-net/dot-net-emitter.yaml
  - docs/reqstream/api-mark-dot-net/dot-net-emitter-gradual-disclosure.yaml
  - docs/reqstream/api-mark-dot-net/dot-net-emitter-single-file.yaml
  - docs/reqstream/api-mark-dot-net/type-link-resolver.yaml
  - docs/reqstream/api-mark-dot-net/xml-doc-reader.yaml
  - docs/reqstream/api-mark-msbuild.yaml
  - docs/reqstream/api-mark-msbuild/api-mark-task.yaml
  - docs/reqstream/api-mark-tool.yaml
  - docs/reqstream/api-mark-tool/program.yaml
  - docs/reqstream/api-mark-tool/cli.yaml
  - docs/reqstream/api-mark-tool/cli/context.yaml
  - docs/reqstream/api-mark-tool/self-test.yaml
  - docs/reqstream/api-mark-tool/self-test/validation.yaml
  - docs/reqstream/ots/mono-cecil.yaml
  - docs/reqstream/api-mark-cpp.yaml
  - docs/reqstream/api-mark-cpp/cpp-generator.yaml
  - docs/reqstream/api-mark-cpp/cpp-ast-model.yaml
  - docs/reqstream/api-mark-cpp/clang-ast-parser.yaml
  - docs/reqstream/api-mark-cpp/cpp-emitter.yaml
  - docs/reqstream/api-mark-cpp/cpp-emitter-gradual-disclosure.yaml
  - docs/reqstream/api-mark-cpp/cpp-emitter-single-file.yaml
  - docs/reqstream/api-mark-cpp/cpp-type-link-resolver.yaml
  - docs/reqstream/api-mark-vhdl.yaml
  - docs/reqstream/api-mark-vhdl/vhdl-generator.yaml
  - docs/reqstream/api-mark-vhdl/vhdl-ast-model.yaml
  - docs/reqstream/api-mark-vhdl/vhdl-ast-parser.yaml
  - docs/reqstream/api-mark-vhdl/vhdl-emitter.yaml
  - docs/reqstream/api-mark-vhdl/vhdl-emitter-gradual-disclosure.yaml
  - docs/reqstream/api-mark-vhdl/vhdl-emitter-single-file.yaml
  - docs/reqstream/ots/clang.yaml
  - docs/reqstream/ots/antlr4.yaml
  - docs/reqstream/ots/cpp-ast-net.yaml
  - docs/reqstream/ots/dema-consulting-test-results.yaml
  - docs/reqstream/ots/file-system-globbing.yaml
