//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from vhdl2008.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace ApiMark.Vhdl.VhdlAst.Antlr {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="vhdl2008Parser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface Ivhdl2008Visitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.abstract_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAbstract_literal([NotNull] vhdl2008Parser.Abstract_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.access_type_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccess_type_definition([NotNull] vhdl2008Parser.Access_type_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.actual_designator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActual_designator([NotNull] vhdl2008Parser.Actual_designatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.actual_parameter_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActual_parameter_part([NotNull] vhdl2008Parser.Actual_parameter_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.actual_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActual_part([NotNull] vhdl2008Parser.Actual_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.adding_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdding_operator([NotNull] vhdl2008Parser.Adding_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.aggregate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAggregate([NotNull] vhdl2008Parser.AggregateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.alias_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlias_declaration([NotNull] vhdl2008Parser.Alias_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.alias_designator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlias_designator([NotNull] vhdl2008Parser.Alias_designatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.allocator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAllocator([NotNull] vhdl2008Parser.AllocatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.architecture_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArchitecture_body([NotNull] vhdl2008Parser.Architecture_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.architecture_declarative_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArchitecture_declarative_part([NotNull] vhdl2008Parser.Architecture_declarative_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.architecture_statement_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArchitecture_statement_part([NotNull] vhdl2008Parser.Architecture_statement_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.array_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_constraint([NotNull] vhdl2008Parser.Array_constraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.array_element_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_element_constraint([NotNull] vhdl2008Parser.Array_element_constraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.array_element_resolution"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_element_resolution([NotNull] vhdl2008Parser.Array_element_resolutionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.array_type_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_type_definition([NotNull] vhdl2008Parser.Array_type_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.assertion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssertion([NotNull] vhdl2008Parser.AssertionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.assertion_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssertion_statement([NotNull] vhdl2008Parser.Assertion_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.association_element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssociation_element([NotNull] vhdl2008Parser.Association_elementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.association_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssociation_list([NotNull] vhdl2008Parser.Association_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.attribute_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute_declaration([NotNull] vhdl2008Parser.Attribute_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.attribute_designator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute_designator([NotNull] vhdl2008Parser.Attribute_designatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.attribute_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute_name([NotNull] vhdl2008Parser.Attribute_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.attribute_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute_specification([NotNull] vhdl2008Parser.Attribute_specificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.base"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBase([NotNull] vhdl2008Parser.BaseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.binding_indication"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinding_indication([NotNull] vhdl2008Parser.Binding_indicationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.block_configuration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock_configuration([NotNull] vhdl2008Parser.Block_configurationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.block_declarative_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock_declarative_item([NotNull] vhdl2008Parser.Block_declarative_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.block_declarative_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock_declarative_part([NotNull] vhdl2008Parser.Block_declarative_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.block_header"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock_header([NotNull] vhdl2008Parser.Block_headerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.block_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock_specification([NotNull] vhdl2008Parser.Block_specificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.block_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock_statement([NotNull] vhdl2008Parser.Block_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.block_statement_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock_statement_part([NotNull] vhdl2008Parser.Block_statement_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.case_generate_alternative"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCase_generate_alternative([NotNull] vhdl2008Parser.Case_generate_alternativeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.case_generate_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCase_generate_statement([NotNull] vhdl2008Parser.Case_generate_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.case_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCase_statement([NotNull] vhdl2008Parser.Case_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.case_statement_alternative"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCase_statement_alternative([NotNull] vhdl2008Parser.Case_statement_alternativeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.choice"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChoice([NotNull] vhdl2008Parser.ChoiceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.choices"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChoices([NotNull] vhdl2008Parser.ChoicesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.component_configuration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComponent_configuration([NotNull] vhdl2008Parser.Component_configurationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.component_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComponent_declaration([NotNull] vhdl2008Parser.Component_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.component_instantiation_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComponent_instantiation_statement([NotNull] vhdl2008Parser.Component_instantiation_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.component_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComponent_specification([NotNull] vhdl2008Parser.Component_specificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.composite_type_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComposite_type_definition([NotNull] vhdl2008Parser.Composite_type_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.concurrent_assertion_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConcurrent_assertion_statement([NotNull] vhdl2008Parser.Concurrent_assertion_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.concurrent_conditional_signal_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConcurrent_conditional_signal_assignment([NotNull] vhdl2008Parser.Concurrent_conditional_signal_assignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.concurrent_procedure_call_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConcurrent_procedure_call_statement([NotNull] vhdl2008Parser.Concurrent_procedure_call_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.concurrent_selected_signal_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConcurrent_selected_signal_assignment([NotNull] vhdl2008Parser.Concurrent_selected_signal_assignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.concurrent_signal_assignment_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConcurrent_signal_assignment_statement([NotNull] vhdl2008Parser.Concurrent_signal_assignment_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.concurrent_simple_signal_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConcurrent_simple_signal_assignment([NotNull] vhdl2008Parser.Concurrent_simple_signal_assignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.concurrent_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConcurrent_statement([NotNull] vhdl2008Parser.Concurrent_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondition([NotNull] vhdl2008Parser.ConditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.condition_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondition_clause([NotNull] vhdl2008Parser.Condition_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.conditional_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditional_expression([NotNull] vhdl2008Parser.Conditional_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.conditional_force_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditional_force_assignment([NotNull] vhdl2008Parser.Conditional_force_assignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.conditional_signal_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditional_signal_assignment([NotNull] vhdl2008Parser.Conditional_signal_assignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.conditional_variable_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditional_variable_assignment([NotNull] vhdl2008Parser.Conditional_variable_assignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.conditional_waveform_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditional_waveform_assignment([NotNull] vhdl2008Parser.Conditional_waveform_assignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.conditional_waveforms"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditional_waveforms([NotNull] vhdl2008Parser.Conditional_waveformsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.configuration_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConfiguration_declaration([NotNull] vhdl2008Parser.Configuration_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.configuration_declarative_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConfiguration_declarative_item([NotNull] vhdl2008Parser.Configuration_declarative_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.configuration_declarative_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConfiguration_declarative_part([NotNull] vhdl2008Parser.Configuration_declarative_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.configuration_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConfiguration_item([NotNull] vhdl2008Parser.Configuration_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.configuration_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConfiguration_specification([NotNull] vhdl2008Parser.Configuration_specificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.constant_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstant_declaration([NotNull] vhdl2008Parser.Constant_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.constrained_array_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstrained_array_definition([NotNull] vhdl2008Parser.Constrained_array_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstraint([NotNull] vhdl2008Parser.ConstraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.context_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContext_clause([NotNull] vhdl2008Parser.Context_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.context_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContext_declaration([NotNull] vhdl2008Parser.Context_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.context_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContext_item([NotNull] vhdl2008Parser.Context_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.context_reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContext_reference([NotNull] vhdl2008Parser.Context_referenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.delay_mechanism"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDelay_mechanism([NotNull] vhdl2008Parser.Delay_mechanismContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.design_file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDesign_file([NotNull] vhdl2008Parser.Design_fileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.design_unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDesign_unit([NotNull] vhdl2008Parser.Design_unitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.designator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDesignator([NotNull] vhdl2008Parser.DesignatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.direction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDirection([NotNull] vhdl2008Parser.DirectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.disconnection_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDisconnection_specification([NotNull] vhdl2008Parser.Disconnection_specificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.discrete_range"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDiscrete_range([NotNull] vhdl2008Parser.Discrete_rangeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.element_association"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElement_association([NotNull] vhdl2008Parser.Element_associationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.element_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElement_constraint([NotNull] vhdl2008Parser.Element_constraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.element_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElement_declaration([NotNull] vhdl2008Parser.Element_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.element_resolution"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElement_resolution([NotNull] vhdl2008Parser.Element_resolutionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.element_subtype_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElement_subtype_definition([NotNull] vhdl2008Parser.Element_subtype_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.entity_aspect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntity_aspect([NotNull] vhdl2008Parser.Entity_aspectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.entity_class"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntity_class([NotNull] vhdl2008Parser.Entity_classContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.entity_class_entry"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntity_class_entry([NotNull] vhdl2008Parser.Entity_class_entryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.entity_class_entry_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntity_class_entry_list([NotNull] vhdl2008Parser.Entity_class_entry_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.entity_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntity_declaration([NotNull] vhdl2008Parser.Entity_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.entity_declarative_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntity_declarative_item([NotNull] vhdl2008Parser.Entity_declarative_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.entity_declarative_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntity_declarative_part([NotNull] vhdl2008Parser.Entity_declarative_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.entity_designator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntity_designator([NotNull] vhdl2008Parser.Entity_designatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.entity_header"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntity_header([NotNull] vhdl2008Parser.Entity_headerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.entity_name_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntity_name_list([NotNull] vhdl2008Parser.Entity_name_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.entity_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntity_specification([NotNull] vhdl2008Parser.Entity_specificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.entity_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntity_statement([NotNull] vhdl2008Parser.Entity_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.entity_statement_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntity_statement_part([NotNull] vhdl2008Parser.Entity_statement_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.entity_tag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntity_tag([NotNull] vhdl2008Parser.Entity_tagContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.enumeration_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumeration_literal([NotNull] vhdl2008Parser.Enumeration_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.enumeration_type_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumeration_type_definition([NotNull] vhdl2008Parser.Enumeration_type_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.exit_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExit_statement([NotNull] vhdl2008Parser.Exit_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] vhdl2008Parser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFactor([NotNull] vhdl2008Parser.FactorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.file_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile_declaration([NotNull] vhdl2008Parser.File_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.file_logical_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile_logical_name([NotNull] vhdl2008Parser.File_logical_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.file_open_information"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile_open_information([NotNull] vhdl2008Parser.File_open_informationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.file_type_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile_type_definition([NotNull] vhdl2008Parser.File_type_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.floating_type_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFloating_type_definition([NotNull] vhdl2008Parser.Floating_type_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.for_generate_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor_generate_statement([NotNull] vhdl2008Parser.For_generate_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.force_mode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForce_mode([NotNull] vhdl2008Parser.Force_modeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.formal_parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFormal_parameter_list([NotNull] vhdl2008Parser.Formal_parameter_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.formal_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFormal_part([NotNull] vhdl2008Parser.Formal_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.full_type_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFull_type_declaration([NotNull] vhdl2008Parser.Full_type_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.function_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_call([NotNull] vhdl2008Parser.Function_callContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.function_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_specification([NotNull] vhdl2008Parser.Function_specificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.generate_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGenerate_specification([NotNull] vhdl2008Parser.Generate_specificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.generate_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGenerate_statement([NotNull] vhdl2008Parser.Generate_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.generate_statement_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGenerate_statement_body([NotNull] vhdl2008Parser.Generate_statement_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.generic_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeneric_clause([NotNull] vhdl2008Parser.Generic_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.generic_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeneric_list([NotNull] vhdl2008Parser.Generic_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.generic_map_aspect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeneric_map_aspect([NotNull] vhdl2008Parser.Generic_map_aspectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.graphic_character"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGraphic_character([NotNull] vhdl2008Parser.Graphic_characterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.group_constituent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGroup_constituent([NotNull] vhdl2008Parser.Group_constituentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.group_constituent_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGroup_constituent_list([NotNull] vhdl2008Parser.Group_constituent_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.group_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGroup_declaration([NotNull] vhdl2008Parser.Group_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.group_template_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGroup_template_declaration([NotNull] vhdl2008Parser.Group_template_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.guarded_signal_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGuarded_signal_specification([NotNull] vhdl2008Parser.Guarded_signal_specificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] vhdl2008Parser.IdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.identifier_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier_list([NotNull] vhdl2008Parser.Identifier_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.if_generate_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_generate_statement([NotNull] vhdl2008Parser.If_generate_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_statement([NotNull] vhdl2008Parser.If_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.incomplete_type_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncomplete_type_declaration([NotNull] vhdl2008Parser.Incomplete_type_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.index_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndex_constraint([NotNull] vhdl2008Parser.Index_constraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.index_subtype_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndex_subtype_definition([NotNull] vhdl2008Parser.Index_subtype_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.indexed_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndexed_name([NotNull] vhdl2008Parser.Indexed_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.instantiated_unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstantiated_unit([NotNull] vhdl2008Parser.Instantiated_unitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.instantiation_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstantiation_list([NotNull] vhdl2008Parser.Instantiation_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.interface_constant_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_constant_declaration([NotNull] vhdl2008Parser.Interface_constant_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.interface_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_declaration([NotNull] vhdl2008Parser.Interface_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.interface_file_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_file_declaration([NotNull] vhdl2008Parser.Interface_file_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.interface_function_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_function_specification([NotNull] vhdl2008Parser.Interface_function_specificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.interface_incomplete_type_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_incomplete_type_declaration([NotNull] vhdl2008Parser.Interface_incomplete_type_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.interface_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_list([NotNull] vhdl2008Parser.Interface_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.interface_object_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_object_declaration([NotNull] vhdl2008Parser.Interface_object_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.interface_package_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_package_declaration([NotNull] vhdl2008Parser.Interface_package_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.interface_package_generic_map_aspect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_package_generic_map_aspect([NotNull] vhdl2008Parser.Interface_package_generic_map_aspectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.interface_procedure_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_procedure_specification([NotNull] vhdl2008Parser.Interface_procedure_specificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.interface_signal_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_signal_declaration([NotNull] vhdl2008Parser.Interface_signal_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.interface_subprogram_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_subprogram_declaration([NotNull] vhdl2008Parser.Interface_subprogram_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.interface_subprogram_default"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_subprogram_default([NotNull] vhdl2008Parser.Interface_subprogram_defaultContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.interface_subprogram_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_subprogram_specification([NotNull] vhdl2008Parser.Interface_subprogram_specificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.interface_type_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_type_declaration([NotNull] vhdl2008Parser.Interface_type_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.interface_variable_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_variable_declaration([NotNull] vhdl2008Parser.Interface_variable_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.iteration_scheme"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIteration_scheme([NotNull] vhdl2008Parser.Iteration_schemeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.label_colon"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabel_colon([NotNull] vhdl2008Parser.Label_colonContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.library_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLibrary_clause([NotNull] vhdl2008Parser.Library_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.library_unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLibrary_unit([NotNull] vhdl2008Parser.Library_unitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] vhdl2008Parser.LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.logical_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogical_operator([NotNull] vhdl2008Parser.Logical_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.loop_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoop_statement([NotNull] vhdl2008Parser.Loop_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.mode_rule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMode_rule([NotNull] vhdl2008Parser.Mode_ruleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.multiplying_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplying_operator([NotNull] vhdl2008Parser.Multiplying_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitName([NotNull] vhdl2008Parser.NameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.name_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitName_part([NotNull] vhdl2008Parser.Name_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.next_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNext_statement([NotNull] vhdl2008Parser.Next_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.null_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNull_statement([NotNull] vhdl2008Parser.Null_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.numeric_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumeric_literal([NotNull] vhdl2008Parser.Numeric_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.object_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObject_declaration([NotNull] vhdl2008Parser.Object_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.package_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPackage_body([NotNull] vhdl2008Parser.Package_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.package_body_declarative_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPackage_body_declarative_item([NotNull] vhdl2008Parser.Package_body_declarative_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.package_body_declarative_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPackage_body_declarative_part([NotNull] vhdl2008Parser.Package_body_declarative_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.package_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPackage_declaration([NotNull] vhdl2008Parser.Package_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.package_declarative_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPackage_declarative_item([NotNull] vhdl2008Parser.Package_declarative_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.package_declarative_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPackage_declarative_part([NotNull] vhdl2008Parser.Package_declarative_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.package_header"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPackage_header([NotNull] vhdl2008Parser.Package_headerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.package_instantiation_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPackage_instantiation_declaration([NotNull] vhdl2008Parser.Package_instantiation_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.parameter_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter_specification([NotNull] vhdl2008Parser.Parameter_specificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.physical_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPhysical_literal([NotNull] vhdl2008Parser.Physical_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.physical_type_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPhysical_type_definition([NotNull] vhdl2008Parser.Physical_type_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.port_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPort_clause([NotNull] vhdl2008Parser.Port_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.port_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPort_list([NotNull] vhdl2008Parser.Port_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.port_map_aspect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPort_map_aspect([NotNull] vhdl2008Parser.Port_map_aspectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.prefix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrefix([NotNull] vhdl2008Parser.PrefixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimary([NotNull] vhdl2008Parser.PrimaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.primary_unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimary_unit([NotNull] vhdl2008Parser.Primary_unitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.primary_unit_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimary_unit_declaration([NotNull] vhdl2008Parser.Primary_unit_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.procedure_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcedure_call([NotNull] vhdl2008Parser.Procedure_callContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.procedure_call_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcedure_call_statement([NotNull] vhdl2008Parser.Procedure_call_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.procedure_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcedure_specification([NotNull] vhdl2008Parser.Procedure_specificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.procedural_declarative_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcedural_declarative_item([NotNull] vhdl2008Parser.Procedural_declarative_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.procedural_statement_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcedural_statement_part([NotNull] vhdl2008Parser.Procedural_statement_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.process_declarative_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcess_declarative_item([NotNull] vhdl2008Parser.Process_declarative_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.process_declarative_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcess_declarative_part([NotNull] vhdl2008Parser.Process_declarative_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.process_sensitivity_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcess_sensitivity_list([NotNull] vhdl2008Parser.Process_sensitivity_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.process_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcess_statement([NotNull] vhdl2008Parser.Process_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.process_statement_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcess_statement_part([NotNull] vhdl2008Parser.Process_statement_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.protected_type_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProtected_type_body([NotNull] vhdl2008Parser.Protected_type_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.protected_type_body_declarative_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProtected_type_body_declarative_item([NotNull] vhdl2008Parser.Protected_type_body_declarative_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.protected_type_body_declarative_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProtected_type_body_declarative_part([NotNull] vhdl2008Parser.Protected_type_body_declarative_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.protected_type_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProtected_type_declaration([NotNull] vhdl2008Parser.Protected_type_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.protected_type_declarative_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProtected_type_declarative_item([NotNull] vhdl2008Parser.Protected_type_declarative_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.protected_type_declarative_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProtected_type_declarative_part([NotNull] vhdl2008Parser.Protected_type_declarative_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.protected_type_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProtected_type_definition([NotNull] vhdl2008Parser.Protected_type_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.qualified_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualified_expression([NotNull] vhdl2008Parser.Qualified_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.range_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRange_decl([NotNull] vhdl2008Parser.Range_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.range_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRange_constraint([NotNull] vhdl2008Parser.Range_constraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.record_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRecord_constraint([NotNull] vhdl2008Parser.Record_constraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.record_element_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRecord_element_constraint([NotNull] vhdl2008Parser.Record_element_constraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.record_element_resolution"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRecord_element_resolution([NotNull] vhdl2008Parser.Record_element_resolutionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.record_resolution"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRecord_resolution([NotNull] vhdl2008Parser.Record_resolutionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.record_type_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRecord_type_definition([NotNull] vhdl2008Parser.Record_type_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.relation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelation([NotNull] vhdl2008Parser.RelationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.relational_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelational_operator([NotNull] vhdl2008Parser.Relational_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.report_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReport_statement([NotNull] vhdl2008Parser.Report_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.resolution_indication"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitResolution_indication([NotNull] vhdl2008Parser.Resolution_indicationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.return_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturn_statement([NotNull] vhdl2008Parser.Return_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.scalar_type_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScalar_type_definition([NotNull] vhdl2008Parser.Scalar_type_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.secondary_unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSecondary_unit([NotNull] vhdl2008Parser.Secondary_unitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.secondary_unit_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSecondary_unit_declaration([NotNull] vhdl2008Parser.Secondary_unit_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.selected_expressions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelected_expressions([NotNull] vhdl2008Parser.Selected_expressionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.selected_force_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelected_force_assignment([NotNull] vhdl2008Parser.Selected_force_assignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.selected_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelected_name([NotNull] vhdl2008Parser.Selected_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.selected_signal_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelected_signal_assignment([NotNull] vhdl2008Parser.Selected_signal_assignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.selected_variable_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelected_variable_assignment([NotNull] vhdl2008Parser.Selected_variable_assignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.selected_waveform_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelected_waveform_assignment([NotNull] vhdl2008Parser.Selected_waveform_assignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.selected_waveforms"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelected_waveforms([NotNull] vhdl2008Parser.Selected_waveformsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.sensitivity_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSensitivity_clause([NotNull] vhdl2008Parser.Sensitivity_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.sensitivity_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSensitivity_list([NotNull] vhdl2008Parser.Sensitivity_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.sequence_of_statements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSequence_of_statements([NotNull] vhdl2008Parser.Sequence_of_statementsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.sequential_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSequential_statement([NotNull] vhdl2008Parser.Sequential_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.shift_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShift_expression([NotNull] vhdl2008Parser.Shift_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.shift_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShift_operator([NotNull] vhdl2008Parser.Shift_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.signal_assignment_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSignal_assignment_statement([NotNull] vhdl2008Parser.Signal_assignment_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.signal_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSignal_declaration([NotNull] vhdl2008Parser.Signal_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.signal_kind"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSignal_kind([NotNull] vhdl2008Parser.Signal_kindContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.signal_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSignal_list([NotNull] vhdl2008Parser.Signal_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.signature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSignature([NotNull] vhdl2008Parser.SignatureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.simple_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimple_expression([NotNull] vhdl2008Parser.Simple_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.simple_force_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimple_force_assignment([NotNull] vhdl2008Parser.Simple_force_assignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.simple_release_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimple_release_assignment([NotNull] vhdl2008Parser.Simple_release_assignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.simple_signal_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimple_signal_assignment([NotNull] vhdl2008Parser.Simple_signal_assignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.simple_waveform_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimple_waveform_assignment([NotNull] vhdl2008Parser.Simple_waveform_assignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.simple_variable_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimple_variable_assignment([NotNull] vhdl2008Parser.Simple_variable_assignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.slice_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSlice_name([NotNull] vhdl2008Parser.Slice_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.subprogram_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubprogram_body([NotNull] vhdl2008Parser.Subprogram_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.subprogram_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubprogram_declaration([NotNull] vhdl2008Parser.Subprogram_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.subprogram_declarative_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubprogram_declarative_item([NotNull] vhdl2008Parser.Subprogram_declarative_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.subprogram_declarative_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubprogram_declarative_part([NotNull] vhdl2008Parser.Subprogram_declarative_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.subprogram_header"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubprogram_header([NotNull] vhdl2008Parser.Subprogram_headerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.subprogram_instantiation_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubprogram_instantiation_declaration([NotNull] vhdl2008Parser.Subprogram_instantiation_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.subprogram_kind"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubprogram_kind([NotNull] vhdl2008Parser.Subprogram_kindContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.subprogram_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubprogram_specification([NotNull] vhdl2008Parser.Subprogram_specificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.subprogram_statement_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubprogram_statement_part([NotNull] vhdl2008Parser.Subprogram_statement_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.subtype_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubtype_declaration([NotNull] vhdl2008Parser.Subtype_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.subtype_indication"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubtype_indication([NotNull] vhdl2008Parser.Subtype_indicationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSuffix([NotNull] vhdl2008Parser.SuffixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTarget([NotNull] vhdl2008Parser.TargetContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm([NotNull] vhdl2008Parser.TermContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.timeout_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTimeout_clause([NotNull] vhdl2008Parser.Timeout_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.tool_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTool_directive([NotNull] vhdl2008Parser.Tool_directiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.type_conversion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_conversion([NotNull] vhdl2008Parser.Type_conversionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.type_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_declaration([NotNull] vhdl2008Parser.Type_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.type_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_definition([NotNull] vhdl2008Parser.Type_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.unbounded_array_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnbounded_array_definition([NotNull] vhdl2008Parser.Unbounded_array_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.use_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUse_clause([NotNull] vhdl2008Parser.Use_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.variable_assignment_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_assignment_statement([NotNull] vhdl2008Parser.Variable_assignment_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.variable_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_declaration([NotNull] vhdl2008Parser.Variable_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.wait_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWait_statement([NotNull] vhdl2008Parser.Wait_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.waveform"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWaveform([NotNull] vhdl2008Parser.WaveformContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdl2008Parser.waveform_element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWaveform_element([NotNull] vhdl2008Parser.Waveform_elementContext context);
}
} // namespace ApiMark.Vhdl.VhdlAst.Antlr
